<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>AutomaticRain</AssemblyName>
    <Version>1.1.1</Version>
    <ApplicationIcon>Pictures\Raindrop.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Pictures\Raindrop.ico" LogicalName="AutomaticRain.Raindrop.ico" />
  </ItemGroup>
</Project>
